name: release
on:
  push:
    branches:
      - main
      - "chore/add_package_publish"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: recursive
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: clippy
        override: true
    - name: Build
      run: cargo +nightly build --release
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      with:
        args: "target/release/cli"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

